<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>PRism Review — {{ $pr->title }}</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; color:#111827; font-size:12px; }
        h1 { font-size:18px; margin:0 0 4px; }
        h2 { font-size:14px; margin:24px 0 8px; padding-bottom:4px; border-bottom:1px solid #e5e7eb; }
        .muted { color:#6b7280; font-size:11px; }
        .meta { margin:8px 0 16px; }
        .meta span { display:inline-block; margin-right:12px; }
        .score-box { display:inline-block; padding:12px 18px; border-radius:6px; margin:8px 0; }
        .score-good { background:#dcfce7; color:#166534; }
        .score-mid  { background:#fef3c7; color:#92400e; }
        .score-bad  { background:#fee2e2; color:#991b1b; }
        .issue { border:1px solid #e5e7eb; border-radius:6px; padding:10px; margin:8px 0; }
        .file { font-family: Courier, monospace; font-size:10px; color:#374151; background:#f3f4f6; padding:2px 6px; border-radius:3px; display:inline-block; }
        .sev { font-size:10px; padding:2px 6px; border-radius:99px; display:inline-block; font-weight:600; }
        .sev-critical   { background:#fee2e2; color:#991b1b; }
        .sev-warning    { background:#fef3c7; color:#92400e; }
        .sev-suggestion { background:#e0e7ff; color:#3730a3; }
        .empty { color:#6b7280; font-style:italic; }
    </style>
</head>
<body>
    <h1>PRism AI Review</h1>
    <div class="muted">{{ $pr->repository?->full_name }} · PR #{{ $pr->pr_number }}</div>
    <h2 style="border:0; margin-top:8px;">{{ $pr->title }}</h2>
    <div class="meta muted">
        <span>Author: <strong>{{ $pr->author }}</strong></span>
        <span>{{ $pr->head_branch }} → {{ $pr->base_branch }}</span>
        <span>Status: {{ $pr->status }}</span>
    </div>

    @if ($review)
        @php
            $s = $review->overall_score;
            $cls = $s === null ? '' : ($s > 70 ? 'score-good' : ($s >= 40 ? 'score-mid' : 'score-bad'));
        @endphp
        <div class="score-box {{ $cls }}">
            Overall score: <strong>{{ $s ?? 'N/A' }}/100</strong>
        </div>

        @if ($review->summary)
            <h2>Summary</h2>
            <p style="line-height:1.5; white-space:pre-line;">{{ $review->summary }}</p>
        @endif

        @foreach (['security' => 'Security Issues', 'performance' => 'Performance Issues', 'code_quality' => 'Code Quality Issues'] as $key => $label)
            <h2>{{ $label }}</h2>
            @php $issues = $review->{$key.'_issues'} ?? []; @endphp
            @if (empty($issues))
                <p class="empty">No issues detected.</p>
            @else
                @foreach ($issues as $issue)
                    <div class="issue">
                        <span class="sev sev-{{ $issue['severity'] ?? 'suggestion' }}">{{ strtoupper($issue['severity'] ?? 'suggestion') }}</span>
                        @if (! empty($issue['file']))
                            <span class="file">{{ $issue['file'] }}{{ ! empty($issue['line']) ? ':'.$issue['line'] : '' }}</span>
                        @endif
                        <p style="margin:6px 0 0;">{{ $issue['comment'] ?? '' }}</p>
                    </div>
                @endforeach
            @endif
        @endforeach

        <p class="muted" style="margin-top:24px;">Generated by {{ $review->ai_model_used ?? '—' }}</p>
    @else
        <p class="empty">No review available yet.</p>
    @endif
</body>
</html>
