import { PRIORITY_LABELS, SCALE_PROFILES, type Blueprint } from './blueprint';

/**
 * A blueprint as a Markdown design doc, for committing next to the code it
 * describes (docs/design/*.md, an ADR folder, a pull request description).
 *
 * The web page is where a design is read once. The repository is where it is
 * read for the next two years, by people who were not in the room — so the
 * export is a first-class output rather than an afterthought.
 */
function escapeCell(value: string): string {
  return value.replace(/\|/g, '\\|').replace(/\n/g, ' ');
}

function table(headers: string[], rows: string[][]): string {
  if (rows.length === 0) {
    return '';
  }

  return (
    `| ${headers.join(' | ')} |\n` +
    `| ${headers.map(() => '---').join(' | ')} |\n` +
    rows.map((row) => `| ${row.map(escapeCell).join(' | ')} |`).join('\n') +
    '\n\n'
  );
}

function bullets(items: string[]): string {
  return items.length === 0 ? '' : items.map((item) => `- ${item}`).join('\n') + '\n\n';
}

function section(title: string, body: string): string {
  return body.trim() === '' ? '' : `## ${title}\n\n${body}`;
}

export function renderBlueprintMarkdown(blueprint: Blueprint): string {
  const { brief } = blueprint;
  const priorities = brief.priorities.map((priority) => PRIORITY_LABELS[priority]).join(', ');

  let out = `# ${blueprint.title || 'System design'}\n\n`;

  out += `> Generated by PRism Design Studio on ${blueprint.created_at.slice(0, 10)}`;
  out += blueprint.source === 'ai' && blueprint.model ? ` with \`${blueprint.model}\`` : '';
  out += '. A starting point for discussion, not a decision record — review it like any other design.\n\n';

  if (blueprint.notice) {
    out += `> **Note:** ${blueprint.notice}\n\n`;
  }

  out += section(
    'Context',
    `${brief.product.trim()}\n\n` +
      `- **Scale:** ${SCALE_PROFILES[brief.scale].label} — ${SCALE_PROFILES[brief.scale].load}\n` +
      (priorities ? `- **Priorities:** ${priorities}\n` : '') +
      (brief.constraints.trim() ? `- **Constraints:** ${brief.constraints.trim()}\n` : '') +
      '\n',
  );

  out += section(
    'Overview',
    (blueprint.architecture_style ? `**Style:** ${blueprint.architecture_style}\n\n` : '') +
      (blueprint.summary ? `${blueprint.summary}\n\n` : ''),
  );

  out += section(
    'Components',
    table(
      ['Component', 'Responsibility', 'Technology', 'Why'],
      blueprint.components.map((c) => [c.name, c.responsibility, c.technology, c.why]),
    ),
  );

  out += section(
    'Data stores',
    table(
      ['Store', 'Kind', 'Holds', 'Why'],
      blueprint.data_stores.map((d) => [d.name, d.kind, d.holds, d.why]),
    ),
  );

  out += section(
    'Main request flow',
    blueprint.request_flow.length === 0
      ? ''
      : blueprint.request_flow.map((step, index) => `${index + 1}. ${step}`).join('\n') + '\n\n',
  );

  out += section(
    'Failure modes',
    table(
      ['Failure', 'Impact', 'Mitigation', 'Detection'],
      blueprint.failure_modes.map((f) => [f.failure, f.impact, f.mitigation, f.detection]),
    ),
  );

  out += section(
    'Reliability patterns',
    table(
      ['Pattern', 'Where', 'Why'],
      blueprint.reliability.map((r) => [r.pattern, r.where, r.why]),
    ),
  );

  out += section(
    'Service level objectives',
    table(['SLO', 'Target'], blueprint.slos.map((s) => [s.name, s.target])),
  );

  out += section(
    'Scaling plan',
    table(
      ['Stage', 'Trigger', 'Changes'],
      blueprint.scaling_stages.map((s) => [s.stage, s.trigger, s.changes]),
    ),
  );

  out += section(
    'Trade-offs',
    table(
      ['Decision', 'Chosen', 'Alternative', 'Why'],
      blueprint.tradeoffs.map((t) => [t.decision, t.chosen, t.alternative, t.why]),
    ),
  );

  out += section('Security', bullets(blueprint.security));
  out += section('Observability', bullets(blueprint.observability));
  out += section('Risks', bullets(blueprint.risks));

  out += section(
    'First milestones',
    blueprint.first_milestones.length === 0
      ? ''
      : blueprint.first_milestones.map((step, index) => `${index + 1}. ${step}`).join('\n') + '\n\n',
  );

  out += section(
    'Production readiness checklist',
    blueprint.readiness_checklist.map((r) => `- [ ] ${r.item} _${r.why}_`).join('\n') + '\n',
  );

  return out.trimEnd() + '\n';
}
