services:
  - type: web
    name: prism
    runtime: docker
    plan: free
    region: singapore
    branch: main
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        sync: false
      - key: APP_URL
        sync: false
      - key: LOG_CHANNEL
        value: stack
      - key: LOG_LEVEL
        value: info
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_URL
        sync: false
      - key: CACHE_DRIVER
        value: redis
      - key: QUEUE_CONNECTION
        value: database
      - key: SESSION_DRIVER
        value: database
      - key: REDIS_URL
        sync: false
      - key: GITHUB_CLIENT_ID
        sync: false
      - key: GITHUB_CLIENT_SECRET
        sync: false
      - key: GITHUB_REDIRECT_URI
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: MAIL_MAILER
        value: resend
      - key: MAIL_FROM_ADDRESS
        value: onboarding@resend.dev
      - key: MAIL_FROM_NAME
        value: PRism AI
