import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { PromptBuilderService, type ReviewTarget } from './prompt-builder.service';

/**
 * The strongest parity guarantee in the slice.
 *
 * The fixtures were generated by reflecting the real Laravel job classes, not
 * hand-copied — so what they record is exactly what PHP produced.
 *
 * They are FROZEN now: the Laravel source and its generator were deleted once
 * the port was complete, so they can no longer be regenerated. That is fine,
 * and arguably better — they are a fixed record of the behaviour this port
 * promised to preserve, and any future edit to the prompts has to break this
 * test deliberately rather than drift past it.
 */
interface PromptFixture {
  languages: string[];
  prompt: string;
}

type FixtureFile = Record<'commit' | 'pull_request', Record<string, PromptFixture>>;

const fixtures = JSON.parse(
  readFileSync(join(__dirname, '..', '..', 'test', 'fixtures', 'system-prompts.json'), 'utf8'),
) as FixtureFile;

const TARGETS: { key: keyof FixtureFile; target: ReviewTarget }[] = [
  { key: 'commit', target: 'commit' },
  { key: 'pull_request', target: 'pull request' },
];

describe('PromptBuilderService', () => {
  const builder = new PromptBuilderService();

  describe.each(TARGETS)('buildSystemPrompt for $target', ({ key, target }) => {
    const cases = Object.entries(fixtures[key]);

    it.each(cases)('matches the Laravel prompt for %s', (_name, fixture) => {
      expect(builder.buildSystemPrompt(fixture.languages, target)).toBe(fixture.prompt);
    });
  });

  it('names the subject in both places, which is the only diff between targets', () => {
    const commit = builder.buildSystemPrompt([], 'commit');
    const pr = builder.buildSystemPrompt([], 'pull request');

    expect(commit).toContain('reviewing a commit.');
    expect(commit).toContain('A clean commit with only minor suggestions');
    expect(pr).toContain('reviewing a pull request.');
    expect(pr).toContain('A clean pull request with only minor suggestions');
    expect(commit.replace(/commit/g, 'pull request')).toBe(pr);
  });

  describe('getLanguageRules', () => {
    it('returns nothing for languages Laravel has no rules for', () => {
      expect(builder.getLanguageRules(['Ruby', 'Java'])).toEqual([]);
    });

    it('shares one rule set between JavaScript and TypeScript', () => {
      const js = builder.getLanguageRules(['JavaScript']);

      expect(builder.getLanguageRules(['TypeScript'])).toEqual(js);
      expect(builder.getLanguageRules(['JavaScript', 'TypeScript'])).toEqual(js);
    });

    it('concatenates in PHP, JS, Python, Go order regardless of input order', () => {
      const rules = builder.getLanguageRules(['Go', 'Python', 'JavaScript', 'PHP']);

      expect(rules[0]).toBe('Detect N+1 query patterns (loops with model calls)');
      expect(rules[6]).toBe('Flag console.log statements left in production code');
      expect(rules.at(-1)).toBe('Detect missing context propagation');
    });
  });

  describe('buildFixesPrompt', () => {
    const layers = {
      security: [{ file: 'a.ts', line: 3, severity: 'critical' as const, comment: 'bad' }],
      performance: [],
      code_quality: [],
    };

    it('uses a single-line skeleton for commits and a block for pull requests', () => {
      const commit = builder.buildFixesPrompt(layers, 'diff', 'commit');
      const pr = builder.buildFixesPrompt(layers, 'diff', 'pull request');

      expect(commit).toContain('{ "fixes": [ { "layer": "security|performance|code_quality"');
      expect(commit).toContain('"problematic_code": "the bad code snippet",');
      expect(pr).toContain('      "problematic_code": "the bad code snippet (2-5 lines)",\n');
      expect(pr).toContain('"explanation": "why this fix is better (1-2 sentences)"');
    });

    it('truncates the diff at 4000 characters', () => {
      const prompt = builder.buildFixesPrompt(layers, 'x'.repeat(5000), 'commit');

      expect(prompt).toContain(`Diff context (first 4000 chars):\n${'x'.repeat(4000)}\n\n`);
      expect(prompt).not.toContain('x'.repeat(4001));
    });

    it('escapes non-ASCII the way PHP json_encode does', () => {
      const prompt = builder.buildFixesPrompt(
        {
          security: [{ file: 'é.ts', line: 1, severity: 'warning', comment: 'naïve' }],
          performance: [],
          code_quality: [],
        },
        'diff',
        'commit',
      );

      expect(prompt).toContain('\\u00e9.ts');
      expect(prompt).toContain('na\\u00efve');
      expect(prompt).not.toContain('é.ts');
    });

    it('indents the issues JSON with four spaces, as JSON_PRETTY_PRINT does', () => {
      const prompt = builder.buildFixesPrompt(layers, 'diff', 'commit');

      expect(prompt).toContain('Issues:\n{\n    "security": [\n');
    });
  });
});
