import { dirname, join } from 'node:path';
import { Injectable } from '@nestjs/common';
import type { Content, TDocumentDefinitions } from 'pdfmake/interfaces';
import * as pdfMake from 'pdfmake';
import type { PullRequest, Review, ReviewIssue } from '../../database/entities';

/**
 * Replaces Barryvdh\DomPDF rendering resources/views/pdf/review.blade.php.
 *
 * WHY NOT A HEADLESS BROWSER: Puppeteer would reproduce the Blade template
 * exactly, but Chromium needs 200-300MB of RAM on a box that already runs the
 * HTTP server and the BullMQ worker inside 512MB — the same ceiling that
 * caused the php-fpm OOM crash-loop (commit 5eca1c6). pdfmake is pure JS and
 * costs a few MB.
 *
 * The trade: this is a close reproduction of the template, not a pixel match.
 * Same content, same section order, same score and severity colour coding,
 * different font (Roboto rather than DejaVu Sans) and slightly different
 * spacing.
 */
const COLORS = {
  text: '#111827',
  muted: '#6b7280',
  border: '#e5e7eb',
  chipBg: '#f3f4f6',
  chipText: '#374151',
  scoreGood: { bg: '#dcfce7', fg: '#166534' },
  scoreMid: { bg: '#fef3c7', fg: '#92400e' },
  scoreBad: { bg: '#fee2e2', fg: '#991b1b' },
  critical: { bg: '#fee2e2', fg: '#991b1b' },
  warning: { bg: '#fef3c7', fg: '#92400e' },
  suggestion: { bg: '#e0e7ff', fg: '#3730a3' },
};

const LAYERS: { key: 'security' | 'performance' | 'code_quality'; label: string }[] = [
  { key: 'security', label: 'Security Issues' },
  { key: 'performance', label: 'Performance Issues' },
  { key: 'code_quality', label: 'Code Quality Issues' },
];

@Injectable()
export class PdfReportService {
  /**
   * Font paths are resolved through require.resolve, not written relative to
   * the repository root: the process cwd on Render is not this file's
   * directory, and a bare "node_modules/..." path would fail to load at
   * runtime while working fine in local development.
   *
   * Registered once for the process — addFonts() mutates pdfmake's module
   * state, so calling it per request would be pure waste.
   */
  private static readonly fontsRegistered = PdfReportService.registerFonts();

  private static registerFonts(): true {
    const dir = join(dirname(require.resolve('pdfmake/package.json')), 'fonts', 'Roboto');

    // Lock pdfmake down before any document is built. Issue text in these
    // reports originates from AI output, and pdfmake resolves paths and URLs
    // found in a document definition — so deny both outright, allowing only
    // the bundled font files. Without this it warns, and rightly so.
    pdfMake.setUrlAccessPolicy(() => false);
    pdfMake.setLocalAccessPolicy((path: string) => path.startsWith(dir));

    pdfMake.addFonts({
      Roboto: {
        normal: join(dir, 'Roboto-Regular.ttf'),
        bold: join(dir, 'Roboto-Medium.ttf'),
        italics: join(dir, 'Roboto-Italic.ttf'),
        bolditalics: join(dir, 'Roboto-MediumItalic.ttf'),
      },
    });

    return true;
  }

  /** Laravel: PRism-Review-PR{n}.pdf */
  filenameFor(pr: PullRequest): string {
    return `PRism-Review-PR${pr.prNumber}.pdf`;
  }

  async render(pr: PullRequest, review: Review | null): Promise<Buffer> {
    void PdfReportService.fontsRegistered;

    return pdfMake.createPdf(this.definition(pr, review)).getBuffer();
  }

  private definition(pr: PullRequest, review: Review | null): TDocumentDefinitions {
    const content: Content[] = [
      { text: 'PRism AI Review', fontSize: 18, bold: true, margin: [0, 0, 0, 4] },
      {
        text: `${pr.repository?.fullName ?? ''} · PR #${pr.prNumber}`,
        fontSize: 11,
        color: COLORS.muted,
      },
      { text: pr.title, fontSize: 14, bold: true, margin: [0, 8, 0, 0] },
      {
        text: `Author: ${pr.author}    ${pr.headBranch} → ${pr.baseBranch}    Status: ${pr.status}`,
        fontSize: 11,
        color: COLORS.muted,
        margin: [0, 8, 0, 16],
      },
    ];

    if (!review) {
      content.push({ text: 'No review available yet.', italics: true, color: COLORS.muted });

      return this.wrap(pr, content);
    }

    content.push(this.scoreBox(review.overallScore));

    if (review.summary) {
      content.push(this.heading('Summary'));
      content.push({ text: review.summary, fontSize: 12, lineHeight: 1.5 });
    }

    for (const { key, label } of LAYERS) {
      content.push(this.heading(label));

      const issues = this.issuesFor(review, key);

      if (issues.length === 0) {
        content.push({ text: 'No issues detected.', italics: true, color: COLORS.muted });
        continue;
      }

      for (const issue of issues) {
        content.push(this.issueCard(issue));
      }
    }

    content.push({
      text: `Generated by ${review.aiModelUsed ?? '—'}`,
      fontSize: 11,
      color: COLORS.muted,
      margin: [0, 24, 0, 0],
    });

    return this.wrap(pr, content);
  }

  private wrap(pr: PullRequest, content: Content[]): TDocumentDefinitions {
    return {
      info: { title: `PRism Review — ${pr.title}` },
      pageMargins: [40, 40, 40, 40],
      defaultStyle: { font: 'Roboto', fontSize: 12, color: COLORS.text },
      content,
    };
  }

  private heading(text: string): Content {
    return {
      text,
      fontSize: 14,
      bold: true,
      margin: [0, 24, 0, 8],
      // Stands in for the Blade template's border-bottom on h2.
      decoration: 'underline',
      decorationColor: COLORS.border,
    };
  }

  /** Blade: > 70 green, >= 40 amber, else red. Note >= 40, not > 40. */
  private scoreBox(score: number | null): Content {
    const palette =
      score === null
        ? { bg: COLORS.chipBg, fg: COLORS.chipText }
        : score > 70
          ? COLORS.scoreGood
          : score >= 40
            ? COLORS.scoreMid
            : COLORS.scoreBad;

    return {
      table: {
        body: [
          [
            {
              text: `Overall score: ${score ?? 'N/A'}/100`,
              bold: true,
              color: palette.fg,
              fillColor: palette.bg,
              margin: [8, 6, 8, 6],
            },
          ],
        ],
      },
      layout: 'noBorders',
      margin: [0, 8, 0, 8],
    };
  }

  private issueCard(issue: ReviewIssue): Content {
    const severity = issue.severity ?? 'suggestion';
    const palette = COLORS[severity as keyof typeof COLORS] as { bg: string; fg: string };
    const location = issue.file
      ? `${issue.file}${issue.line ? `:${issue.line}` : ''}`
      : null;

    const header: Content[] = [
      {
        text: severity.toUpperCase(),
        fontSize: 10,
        bold: true,
        color: palette.fg,
        fillColor: palette.bg,
        margin: [4, 2, 4, 2],
      },
    ];

    if (location) {
      header.push({
        text: location,
        fontSize: 10,
        color: COLORS.chipText,
        fillColor: COLORS.chipBg,
        margin: [4, 2, 4, 2],
      });
    }

    return {
      table: {
        widths: ['*'],
        body: [
          [
            {
              stack: [
                { columns: header, columnGap: 6 },
                { text: issue.comment ?? '', margin: [0, 6, 0, 0] },
              ],
              margin: [6, 6, 6, 6],
            },
          ],
        ],
      },
      layout: {
        hLineColor: () => COLORS.border,
        vLineColor: () => COLORS.border,
        hLineWidth: () => 1,
        vLineWidth: () => 1,
      },
      margin: [0, 8, 0, 0],
    };
  }

  private issuesFor(review: Review, key: 'security' | 'performance' | 'code_quality'): ReviewIssue[] {
    const value =
      key === 'security'
        ? review.securityIssues
        : key === 'performance'
          ? review.performanceIssues
          : review.codeQualityIssues;

    return Array.isArray(value) ? value : [];
  }
}
